### ISSUE TITLE
[nhóm 39 - sachmem - TA3SBT - 03] Thiếu thông tin phụ lục

### ISSUE THREAD

**Issue by quangdd5757** [truonganhhoang/kiemthu2015#130]
Hầu hết các lesson đều chưa có đầy đủ thông tin trong chức năng phụ lục
![screencapture-demo-sachmem-com-books-5-exercises-629-1448540287169](https://cloud.githubusercontent.com/assets/14195743/11422908/7439212a-9472-11e5-9f27-26be3de0274b.png)

**Comment by suongdv** [comment]
hầu như các bài đều như vậy
