### ISSUE TITLE
[nhóm 39 - sachmem - TA3SBT - 09]sai nội dung

### ISSUE THREAD

**Issue by suongdv** [truonganhhoang/kiemthu2015#135]

**Comment by suongdv** [comment]
![10](https://cloud.githubusercontent.com/assets/14195909/11423071/db25b316-9473-11e5-9354-a791b9770933.png)
sai từ 'friens'

**Comment by quangdd5757** [comment]
![screencapture-demo-sachmem-com-books-5-exercises-1898-1448541924664](https://cloud.githubusercontent.com/assets/14195743/11423377/5e057daa-9476-11e5-9682-09e54ab590e5.png)
bài C - 1, bài yêu cầu đọc và trở lời, nhưng phụ lục lại yêu cầu điền từ
![screencapture-demo-sachmem-com-books-5-exercises-1899-1448544252430](https://cloud.githubusercontent.com/assets/14195743/11423962/b491d38a-947b-11e5-9a47-630768a4ffd3.png)
![screencapture-demo-sachmem-com-books-5-exercises-1900-1448546062205](https://cloud.githubusercontent.com/assets/14195743/11424453/ecc29f88-947f-11e5-84f8-cddf8e912c75.png)
và unit 4 bài D-1

**Comment by quangdd5757** [comment]
![screencapture-demo-sachmem-com-books-5-exercises-916-1448543011677](https://cloud.githubusercontent.com/assets/14195743/11423662/e8865aba-9478-11e5-86f5-0fe3a92c8308.png)
đáp án "I am" vẫn có thể chấp nhận, nhưng chỉ check chỉ nhận i'm và I'm

**Comment by quangdd5757** [comment]
tương tự với unit 2 bài A -2, bài E-1

**Comment by quangdd5757** [comment]
![screencapture-demo-sachmem-com-books-5-exercises-1278-1448546450545](https://cloud.githubusercontent.com/assets/14195743/11424614/2b7721bc-9481-11e5-8e73-bd0a6c32fe58.png)
Draw your best friend in the box. ??? box ở đâu?

**Comment by phucdh57** [comment]
![image](https://cloud.githubusercontent.com/assets/13212076/11458266/4694742a-96ef-11e5-9041-af345416ec94.png)
the robot in the image is black not is gray
