### ISSUE TITLE
[Khuất Thái Hoàng-Nhóm12] Không hiển thị được trang và vẫn có tiếng nói

### ISSUE THREAD

**Issue by hoangkt57** [truonganhhoang/kiemthu2015#145]
Không hiển thị được trang và vẫn có tiếng nói
http://demo.sachmem.com/books/4/exercises/77
http://demo.sachmem.com/books/4/exercises/78
![image](https://cloud.githubusercontent.com/assets/14309400/11445553/bead892e-955f-11e5-82d8-cae50e4ef79f.png)

**Comment by NguyenThaiHoc** [comment]
http://demo.sachmem.com/books/4/exercises/77
