### ISSUE TITLE
[Nhóm 1_Phạm Minh Đức_Unit8+Unit9]

### ISSUE THREAD

**Issue by minhducit94** [truonganhhoang/kiemthu2015#212]
Bug 1 (Tất cả các phần): từ vựng đều không liên quan đến bài học và đều có lỗi dịch nghĩa black là màu đen U9
![bug1](https://cloud.githubusercontent.com/assets/14245245/11456392/bd397250-96b9-11e5-8532-d4c7fbeff242.png)

**Comment by truonganhhoang** [comment]
Khi log bug em phải làm mỗi màn hình một issue, chứ không gộp vào một thế này.

**Comment by minhducit94** [comment]
Bug 2 (Những phần có chấm điểm): nếu làm sai thì chấm điểm là "not very good", nhưng làm đúng vẫn bị chấm điểm là "not very good"
Unit 8: phần 1-2, 1-4, 1-5, 2-2, 2-4, 2-6, 3-4, 4-5
Unit 9: phần 1-2, 1-4, 1-5, 1-6, 2-2, 2-4, 2-5, 3-4, 4-5
![bug2](https://cloud.githubusercontent.com/assets/14245245/11456412/91b5bc46-96ba-11e5-8664-eb485a66df0c.png)

**Comment by minhducit94** [comment]
Bug 3 (một số phần): không kiểm tra và không chấm điểm được người dùng làm đúng hay sai
Unit 8: 2-5, 3-2
Unit 9: 3-2
![bug3](https://cloud.githubusercontent.com/assets/14245245/11456434/3e1afa96-96bb-11e5-9136-e173cbd66663.png)

**Comment by minhducit94** [comment]
Bug 4 (các phần Let's talk): không reset được
Unit 8: 1-3, 2-3
Unit 9: 1-3, 2-3
![bug4](https://cloud.githubusercontent.com/assets/14245245/11456448/d20393f8-96bb-11e5-9eda-537aaf3a1367.png)

**Comment by minhducit94** [comment]
Bug 5 (Unit 8 phần 1-6: Let's play): không hiển thị nội dung bài học
![bug5](https://cloud.githubusercontent.com/assets/14245245/11456462/5ecdfb02-96bc-11e5-8849-e10e3ba3d490.png)
